//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Entities.DataEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelManagementDbEntities : DbContext
    {
        public HotelManagementDbEntities()
            : base("name=HotelManagementDbEntities")
        {
        }
    
        public virtual DbSet<tbl_Bookings> tbl_Bookings { get; set; }
        public virtual DbSet<tbl_Hotel> tbl_Hotel { get; set; }
        public virtual DbSet<tbl_Room> tbl_Room { get; set; }
    }
}
